### ISSUE TITLE
Consider enabling no-underscore-dangle rule for TypeScript projects

### ISSUE THREAD

**Issue by scotia673** [ni/javascript-styleguide#36]
Currently, the `no-underscore-dangle` rule is explicitly turned off. However, in TypeScript projects, permitting `_` prefixes on explicitly private members does not usually provide much value. Thoughts on enabling it for just the TypeScript ruleset?

`<edit>`
An interesting TS use case worth thinking about arose in a PR recently where we wanted to have a public getter and a private setter, so the approach taken was to use a private backing field on a public accessor - and `_` was used to clearly distinguish these.
`</edit>`

**Comment by jattasNI** [comment]
We discussed this in our Coding Practices Working Group meeting today. We agreed that the underscore syntax makes sense for backing fields. Our working proposal is to try turning this rule on for TypeScript only with the following config:
```js
"allowAfterThis": true // we think this is necessary to allow accessing private fields with an underscore
"allowAfterSuper": true // we think this is necessary to allow accessing protected fields with an underscore
"allowAfterThisConstructor": false
"enforceInMethodNames": true // this prevents private methods from using an underscore
"allowFunctionParams": true // this is compatible with our recommendation to prefix unused params with an underscore
```

I'll try out this config and see if it behaves as we think it should.

**Comment by jattasNI** [comment]
I tried this config in Web Portal and it resulted in some false positives in places where we are using third party APIs that include an underscore:
```ts
        // app/shared/components/axes-markers/axes-markers.component.ts
        $event.component._$list.css('width', `${dropDownWidth}rem`);

        // app/shared/components/multiple_selection/multiple-selection.component.ts
        e.component._shouldCloseOnItemClick = () => false;
```
It also didn't add much value since it only really enforced no underscores in method names, which is not a common practice. 

I recommend we leave this rule off and instead have manually enforced coding conventions around underscores:

**Proposal** Manual conventions for the following:
1. In JavaScript, allow underscore prefix on fields and methods to mean "intended to be private".
1. In TypeScript, allow underscore prefix on fields when they back a property of the same name.
1. In both, allow underscore prefix on parameter names to indicate that the parameter is intentionally unused.
1. All other uses of underscore prefixes are discouraged.
